// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jlhpoueedzlelthhjtnc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpsaHBvdWVlZHpsZWx0aGhqdG5jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0Nzc1MjUsImV4cCI6MjA2NjA1MzUyNX0.EjYZsqk8SsjDmgW2mdW4IFFwFyObeNVZ9iX3zW31gTA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);